### ISSUE TITLE
Wiki references wrong file

### ISSUE THREAD

**Issue by uli42** [IBM/ibm-spectrum-scale-bridge-for-grafana#138]
https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/wiki/Running-the-IBM-Spectrum-Scale-Performance-Monitoring-Bridge-in-a-docker-container

references ZIMonSensors.cfg, but it should be ZIMonCollector.cfg

**Comment by Helene** [comment]
@uli42 good catch, thanks for opening the issue. I'll fix it

**Comment by Helene** [comment]
fixed 
https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/wiki/Running-the-IBM-Spectrum-Scale-Performance-Monitoring-Bridge-in-a-docker-container
