### ISSUE TITLE
Create a collection of grafana dashboards based on Prometheus Bridge 

### ISSUE THREAD

**Issue by SckyzO** [IBM/ibm-spectrum-scale-bridge-for-grafana#189]
Just as there are dashboards for the Ibm to Grafana bridge but for OpenTSBD, would it be possible to have pre-configured dashboards for Prometheus ?

**Comment by Helene** [comment]
Some examples you can find under:
 https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/tree/master/examples/grafana_dashboards/gpfs_cluster_overview/Prometheus%20as%20Datasource
https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/tree/master/examples/grafana_dashboards/gpfs_health/Prometheus%20as%20Datasource
