### ISSUE TITLE
cannot get metadata from pmcollector

### ISSUE THREAD

**Issue by liaozexian1204** [IBM/ibm-spectrum-scale-bridge-for-grafana#199]
when starting this zimonGrafanaIntf.py application, it reports below and exits after retry
"QueryHandler: getTopology returns no data", the server respond is "503 Connection refused from server"

I checked gpfs gui and pmcollectors are active and running by "systemctl status gpfsgui" and "systemctl status pmcollector"
and zimonGrafanaIntf.py is started at the same host with gpfs gui and pmcollector.

Is there something I missed with the configuration?
what is the serverPort in "GPFS Server" section of config.ini. Is there any CLI that I can check the listening port of queries on pmcollector?

I also find the query Rest APIs are /sysmon/v1/perfmon/topo, but this API can't be found in GPFS doc https://www.ibm.com/docs/en/storage-scale/5.1.9?topic=endpoints-performance-monitoring

**Comment by liaozexian1204** [comment]
my gpfs version is 5.1.6.1,
I got below config in pmcollector config:
fallbackqueryinterface = "0.0.0.0"
fallbackqueryport = "9084"
and bridge config.ini server port is 9084, but cannot connect

**Comment by ps20renar** [comment]
Hallo liaozexian1204,
for installation make at first a 
mmperfmon config show --apikey scale_grafana
Put this key in the config.ini on the key parameter and restart the bridge.

**Comment by liaozexian1204** [comment]
apikey of scale_grafana is already configured, but still cannot connect.
grafana bridge reports the same error: 503 connection refused.
in pmcollector log, it says "ServiceInterface: read 1error: closing socket 127.0.0.1"

**Comment by Helene** [comment]
> apikey of scale_grafana is already configured, but still cannot connect. grafana bridge reports the same error: 503 connection refused. in pmcollector log, it says "ServiceInterface: read 1error: closing socket 127.0.0.1"
> 
> any thoughts?

on the pmcollector node please execute the following commands and put the output here
```
# mmlscluster

# mmhealth node show perfmon -v

# mmsysmonc noderoles list

```

**Comment by liaozexian1204** [comment]
![image](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/assets/44052474/fd543b8c-2fe3-4a0f-9267-685a0b80f72c)
![image](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/assets/44052474/54e9e0a7-a90a-4ebb-8c28-e4c0c3a54ea1)
![image](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/assets/44052474/16b423e5-6aff-4b08-9b35-d36e6ac3531b)
the collector node is gpfs01 in my cluster

**Comment by Helene** [comment]
Are you running the grafana-bridge directly on gpfs01 or on a remote host?
I need probably review your config.ini
How do you start the grafana-bridge?

**Comment by liaozexian1204** [comment]
I think I found the reason - indeed the configuration is incorrect.
pmcollector config:
fallbackqueryinterface="0.0.0.0"
fallbackqueryport="29980"

grafana-bridge config.ini:
serverPort = 29980

after I changed config.ini "serverPort" back to 9980, pmcollector metadata can be retrieved.
It seems that fallbackqueryport is used for other purpose, not for zimon rest api.

thanks, I'm closing this ticket.

**Comment by Helene** [comment]
> I think I found the reason - indeed the configuration is incorrect. pmcollector config: (as in https://www.ibm.com/docs/en/spectrum-control/5.4.4?topic=systems-configuring-collection-performance-data-spectrum-scale) fallbackqueryinterface="0.0.0.0" fallbackqueryport="29980"
> 
> grafana-bridge config.ini: serverPort = 29980
> 
> after I changed config.ini "serverPort" back to 9980, pmcollector metadata can be retrieved. It seems that fallbackqueryport is used for other purpose, not for zimon rest api.
> 
> thanks, I'm closing this ticket.

Oh, you are using perfmon for Spectrum Control, which requires specific port configuration. 
Probably I need to document this case. Thanks for your feedback.
