### ISSUE TITLE
raise cherrypy.HTTPError(404, MSG[404]),KeyError: 404

### ISSUE THREAD

**Issue by lanmoweiwei** [IBM/ibm-spectrum-scale-bridge-for-grafana#241]
When import  Multiple dashboard from  \ibm-spectrum-scale-bridge-for-grafana-7.1.9\examples\grafana_dashboards\Dashboards_to_use_with_Grafana_9.5_and_above\
such as 
Monitoring Filesystems-1692341412466
Memory_utilization-1692362928888
(Linux)Network and general metrics-1692356622068

may cause dashboard load slowly  and cherryPy 404 error and need restart  python3  zimonGrafanaIntf.py --apiKeyValue 

My envirement：
storagescale 5.1.9
grafana v11.2.0 
python3.9.5
bridge v7.1.9
cherryPy version: 18.9.0

(grafana_bridge) [root@storage01 source]# tail -f nohup.out
2024-10-28 10:29 - CP Server Thread-11            - ERROR    - Metric  cannot be found. Please check if the corresponding sensor is configured
2024-10-28 10:29 - CP Server Thread-6             - ERROR    - Metric  cannot be found. Please check if the corresponding sensor is configured
2024-10-28 10:29 - CP Server Thread-4             - ERROR    - Metric  cannot be found. Please check if the corresponding sensor is configured
2024-10-28 10:29 - CP Server Thread-9             - ERROR    - Metric  cannot be found. Please check if the corresponding sensor is configured
2024-10-28 10:32 - MainThread                     - INFO     -  *** IBM Storage Scale bridge for Grafana - Version: 7.1.9 ***
2024-10-28 10:32 - MainThread                     - INFO     - Successfully retrieved MetaData
2024-10-28 10:32 - MainThread                     - INFO     - Received sensors:GPFSDiskCap, GPFSFCM, GPFSFCMDA, GPFSFileset, GPFSFilesetQuota, GPFSInodeCap, GPFSPool, GPFSPoolCap, CPU, DiskFree, GPFSBufMgr, GPFSFilesystem, GPFSFilesystemAPI, GPFSNode, GPFSNodeAPI, GPFSRPCS, GPFSVFSX, GPFSWaiters, Load, Memory, Netstat, Network, TopProc, CTDBDBStats, CTDBStats, Diskstat, GPFSCHMS, GPFSDisk, GPFSEventProducer, GPFSMutex, GPFSNSDDisk, GPFSNSDFS, GPFSNSDPool, GPFSPoolIO, IPFIX, Infiniband, SMBGlobalStats, SMBStats, GPFSPDDisk
2024-10-28 10:32 - MainThread                     - INFO     - Initial cherryPy server engine start have been invoked. Python version: 3.9.5 (default, Oct 22 2024, 10:15:45)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)], cherryPy version: 18.9.0.
2024-10-28 10:32 - MainThread                     - INFO     - server started
2024-10-28 10:55 - AdHocMetaDataUpdate            - WARNING  - Perfmon RESTcall error __ Server responded: 404 The request could not be processed from server
2024-10-28 10:55 - AdHocMetaDataUpdate            - ERROR    - QueryHandler: getTopology returns no data.
2024-10-28 10:55 - AdHocMetaDataUpdate            - ERROR    - Empty results received
Exception in thread AdHocMetaDataUpdate:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/grafana_bridge/bridge-7.1.9/source/utils.py", line 44, in wrapper
    result = f(*args, **kwargs)
  File "/home/grafana_bridge/bridge-7.1.9/source/metadata.py", line 161, in update
    raise cherrypy.HTTPError(404, MSG[404])
KeyError: 404
^C
(grafana_bridge) [root@storage01 source]#

**Comment by Helene** [comment]
@lanmoweiwei it looks like grafana-bridge is loosing connection to the pmcollector permanently. We need to check if your pmcollector setup is running stable.
Please provide the output of 
`# mmperfmon config show`
Also provide the logs (as compressed file) from pcollector node  to which you have connected grafana-bridge.
The logs should be available in the folder /var/log/zimon

**Comment by lanmoweiwei** [comment]
(grafana_bridge) [root@storage01 source]# mmperfmon config show
# This file has been generated automatically and SHOULD NOT
# be edited manually.  It may be overwritten at any point
# in time.

cephMon = "/opt/IBM/zimon/CephMonProxy"
cephRados = "/opt/IBM/zimon/CephRadosProxy"
colCandidates = "storage01.inspur.com", "storage02.inspur.com"
colRedundancy = 2
collectors = {
        host = ""
        port = "4739"
}
config = "/opt/IBM/zimon/ZIMonSensors.cfg"
ctdbstat = ""
daemonize = T
delay_initial_poll = T
hostname = ""
ipfixinterface = "0.0.0.0"
logfile = "/var/log/zimon/ZIMonSensors.log"
loglevel = "info"
mmcmd = "/opt/IBM/zimon/MMCmdProxy"
mmdfcmd = "/opt/IBM/zimon/MMDFProxy"
mmpmon = "/opt/IBM/zimon/MmpmonSockProxy"
piddir = "/var/run"
release = "5.1.9-3"
sensors = {
        name = "CPU"
        period = 1
},
{
        name = "Load"
        period = 1
},
{
        name = "Memory"
        period = 1
},
{
        filter = "netdev_name=veth.*|docker.*|flannel.*|cali.*|cbr.*"
        name = "Network"
        period = 1
},
{
        name = "Netstat"
        period = 10
},
{
        name = "Diskstat"
        period = 0
},
{
        filter = "mountPoint=/.*/docker.*|/.*/kubelet.*"
        name = "DiskFree"
        period = 600
},
{
        name = "Infiniband"
        period = 0
},
{
        name = "GPFSDisk"
        period = 0
},
{
        name = "GPFSFilesystem"
        period = 10
},
{
        name = "GPFSNSDDisk"
        period = 10
        restrict = "nsdNodes"
},
{
        name = "GPFSPoolIO"
        period = 0
},
{
        name = "GPFSVFSX"
        period = 10
},
{
        name = "GPFSIOC"
        period = 0
},
{
        name = "GPFSVIO64"
        period = 0
},
{
        name = "GPFSPDDisk"
        period = 10
        restrict = "nsdNodes"
},
{
        name = "GPFSvFLUSH"
        period = 0
},
{
        name = "GPFSNode"
        period = 10
},
{
        name = "GPFSNodeAPI"
        period = 10
},
{
        name = "GPFSFilesystemAPI"
        period = 10
},
{
        name = "GPFSLROC"
        period = 0
},
{
        name = "GPFSCHMS"
        period = 0
},
{
        name = "GPFSAFM"
        period = 0
},
{
        name = "GPFSAFMFS"
        period = 0
},
{
        name = "GPFSAFMFSET"
        period = 0
},
{
        name = "GPFSRPCS"
        period = 10
},
{
        name = "GPFSWaiters"
        period = 10
},
{
        name = "GPFSFilesetQuota"
        period = 3600
        restrict = "@CLUSTER_PERF_SENSOR"
},
{
        name = "GPFSFileset"
        period = 300
        restrict = "@CLUSTER_PERF_SENSOR"
},
{
        name = "GPFSPool"
        period = 300
        restrict = "@CLUSTER_PERF_SENSOR"
},
{
        name = "GPFSDiskCap"
        period = 86400
        restrict = "@CLUSTER_PERF_SENSOR"
},
{
        name = "GPFSEventProducer"
        period = 0
},
{
        name = "GPFSMutex"
        period = 0
},
{
        name = "GPFSCondvar"
        period = 0
},
{
        name = "TopProc"
        period = 60
},
{
        name = "GPFSQoS"
        period = 0
},
{
        name = "GPFSBufMgr"
        period = 30
},
{
        name = "NFSIO"
        period = 10
        restrict = "cesNodes"
        type = "Generic"
},
{
        name = "SMBStats"
        period = 2
        restrict = "all"
        type = "Generic"
},
{
        name = "SMBGlobalStats"
        period = 2
        restrict = "cesNodes"
        type = "Generic"
},
{
        name = "CTDBStats"
        period = 1
        restrict = "cesNodes"
        type = "Generic"
},
{
        name = "CTDBDBStats"
        period = 1
        restrict = "cesNodes"
        type = "Generic"
},
{
        name = "GPFSFCM"
        period = 60
}
smbstat = ""
(grafana_bridge) [root@storage01 source]#
[ZIMonSensors.log-20241027.gz](https://github.com/user-attachments/files/17551212/ZIMonSensors.log-20241027.gz)
[ZIMonCollector.log-20241029.gz](https://github.com/user-attachments/files/17551213/ZIMonCollector.log-20241029.gz)

**Comment by Helene** [comment]
@lanmoweiwei from the logs I see that the clock on nodes in your cluster is not in sysnc.
```
Line    1: Oct-28 03:24:17  [Warning] Collector: Packet from 1730057052, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line    8: Oct-28 03:39:18  [Warning] Collector: Packet from 1730057953, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line   20: Oct-28 03:54:19  [Warning] Collector: Packet from 1730058853, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line   27: Oct-28 04:09:20  [Warning] Collector: Packet from 1730059745, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line   48: Oct-28 04:24:21  [Warning] Collector: Packet from 1730060646, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line   55: Oct-28 04:39:22  [Warning] Collector: Packet from 1730061547, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line   67: Oct-28 04:54:23  [Warning] Collector: Packet from 1730062448, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line   72: Oct-28 05:09:25  [Warning] Collector: Packet from 1730063359, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line   96: Oct-28 05:24:26  [Warning] Collector: Packet from 1730064260, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line  104: Oct-28 05:39:27  [Warning] Collector: Packet from 1730065152, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  115: Oct-28 05:54:28  [Warning] Collector: Packet from 1730066053, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  122: Oct-28 06:09:29  [Warning] Collector: Packet from 1730066954, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  142: Oct-28 06:24:30  [Warning] Collector: Packet from 1730067855, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  157: Oct-28 06:39:31  [Warning] Collector: Packet from 1730068756, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  168: Oct-28 06:54:32  [Warning] Collector: Packet from 1730069657, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  176: Oct-28 07:09:33  [Warning] Collector: Packet from 1730070558, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  196: Oct-28 07:24:35  [Warning] Collector: Packet from 1730071469, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line  202: Oct-28 07:39:36  [Warning] Collector: Packet from 1730072370, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line  216: Oct-28 07:54:37  [Warning] Collector: Packet from 1730073262, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  224: Oct-28 08:09:38  [Warning] Collector: Packet from 1730074163, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  246: Oct-28 08:24:39  [Warning] Collector: Packet from 1730075073, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line  254: Oct-28 08:39:40  [Warning] Collector: Packet from 1730075965, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  265: Oct-28 08:54:41  [Warning] Collector: Packet from 1730076866, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  273: Oct-28 09:09:42  [Warning] Collector: Packet from 1730077767, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  294: Oct-28 09:24:43  [Warning] Collector: Packet from 1730078668, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  302: Oct-28 09:39:44  [Warning] Collector: Packet from 1730079579, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line  313: Oct-28 09:54:45  [Warning] Collector: Packet from 1730080481, long delay (4 sec) or unsynchronized clocks from 10.25.117.27
	Line  319: Oct-28 10:09:46  [Warning] Collector: Packet from 1730081380, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line  342: Oct-28 10:24:47  [Warning] Collector: Packet from 1730082272, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line  719: Oct-28 10:39:48  [Warning] Collector: Packet from 1730083173, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1107: Oct-28 10:54:49  [Warning] Collector: Packet from 1730084083, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 1119: Oct-28 11:09:50  [Warning] Collector: Packet from 1730084975, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1139: Oct-28 11:24:51  [Warning] Collector: Packet from 1730085876, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1147: Oct-28 11:39:52  [Warning] Collector: Packet from 1730086777, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1161: Oct-28 11:54:53  [Warning] Collector: Packet from 1730087678, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1171: Oct-28 12:09:54  [Warning] Collector: Packet from 1730088589, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 1193: Oct-28 12:24:55  [Warning] Collector: Packet from 1730089480, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1204: Oct-28 12:39:56  [Warning] Collector: Packet from 1730090381, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1219: Oct-28 12:54:57  [Warning] Collector: Packet from 1730091282, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1230: Oct-28 13:09:58  [Warning] Collector: Packet from 1730092183, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1250: Oct-28 13:24:59  [Warning] Collector: Packet from 1730093084, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1257: Oct-28 13:40:00  [Warning] Collector: Packet from 1730093985, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1271: Oct-28 13:55:01  [Warning] Collector: Packet from 1730094886, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 1487: Oct-28 14:10:02  [Warning] Collector: Packet from 1730095787, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 2529: Oct-28 14:25:03  [Warning] Collector: Packet from 1730096688, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3287: Oct-28 14:40:04  [Warning] Collector: Packet from 1730097599, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 3392: Oct-28 14:55:05  [Warning] Collector: Packet from 1730098490, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3587: Oct-28 15:10:06  [Warning] Collector: Packet from 1730099391, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3610: Oct-28 15:25:07  [Warning] Collector: Packet from 1730100292, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3618: Oct-28 15:40:08  [Warning] Collector: Packet from 1730101203, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 3631: Oct-28 15:55:09  [Warning] Collector: Packet from 1730102103, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 3755: Oct-28 16:10:10  [Warning] Collector: Packet from 1730102995, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3816: Oct-28 16:25:11  [Warning] Collector: Packet from 1730103896, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3827: Oct-28 16:40:12  [Warning] Collector: Packet from 1730104797, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3838: Oct-28 16:55:13  [Warning] Collector: Packet from 1730105698, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3847: Oct-28 17:10:14  [Warning] Collector: Packet from 1730106599, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3869: Oct-28 17:25:15  [Warning] Collector: Packet from 1730107500, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3875: Oct-28 17:40:16  [Warning] Collector: Packet from 1730108410, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 3892: Oct-28 17:55:17  [Warning] Collector: Packet from 1730109302, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3901: Oct-28 18:10:18  [Warning] Collector: Packet from 1730110203, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3922: Oct-28 18:25:19  [Warning] Collector: Packet from 1730111104, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3937: Oct-28 18:40:20  [Warning] Collector: Packet from 1730112005, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3947: Oct-28 18:55:21  [Warning] Collector: Packet from 1730112906, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3956: Oct-28 19:10:22  [Warning] Collector: Packet from 1730113807, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3977: Oct-28 19:25:23  [Warning] Collector: Packet from 1730114708, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 3985: Oct-28 19:40:24  [Warning] Collector: Packet from 1730115619, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 3996: Oct-28 19:55:25  [Warning] Collector: Packet from 1730116510, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4002: Oct-28 20:10:26  [Warning] Collector: Packet from 1730117420, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4026: Oct-28 20:25:27  [Warning] Collector: Packet from 1730118312, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4034: Oct-28 20:40:28  [Warning] Collector: Packet from 1730119213, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4045: Oct-28 20:55:29  [Warning] Collector: Packet from 1730120114, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4054: Oct-28 21:10:30  [Warning] Collector: Packet from 1730121015, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4074: Oct-28 21:25:31  [Warning] Collector: Packet from 1730121916, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4082: Oct-28 21:40:32  [Warning] Collector: Packet from 1730122817, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4093: Oct-28 21:55:33  [Warning] Collector: Packet from 1730123718, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4102: Oct-28 22:10:34  [Warning] Collector: Packet from 1730124629, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 4123: Oct-28 22:25:35  [Warning] Collector: Packet from 1730125520, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4129: Oct-28 22:40:36  [Warning] Collector: Packet from 1730126430, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4143: Oct-28 22:55:37  [Warning] Collector: Packet from 1730127322, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4152: Oct-28 23:10:38  [Warning] Collector: Packet from 1730128223, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4172: Oct-28 23:25:39  [Warning] Collector: Packet from 1730129133, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4180: Oct-28 23:40:40  [Warning] Collector: Packet from 1730130025, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4191: Oct-28 23:55:41  [Warning] Collector: Packet from 1730130926, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4200: Oct-29 00:10:42  [Warning] Collector: Packet from 1730131827, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4220: Oct-29 00:25:43  [Warning] Collector: Packet from 1730132728, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4234: Oct-29 00:40:44  [Warning] Collector: Packet from 1730133639, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 4244: Oct-29 00:55:46  [Warning] Collector: Packet from 1730134540, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4250: Oct-29 01:10:47  [Warning] Collector: Packet from 1730135432, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4273: Oct-29 01:25:48  [Warning] Collector: Packet from 1730136333, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4281: Oct-29 01:40:49  [Warning] Collector: Packet from 1730137243, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4292: Oct-29 01:55:50  [Warning] Collector: Packet from 1730138135, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4301: Oct-29 02:10:51  [Warning] Collector: Packet from 1730139036, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4322: Oct-29 02:25:52  [Warning] Collector: Packet from 1730139937, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4330: Oct-29 02:40:53  [Warning] Collector: Packet from 1730140838, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4343: Oct-29 02:55:54  [Warning] Collector: Packet from 1730141749, long delay (5 sec) or unsynchronized clocks from 10.25.117.29
	Line 4352: Oct-29 03:10:56  [Warning] Collector: Packet from 1730142650, long delay (6 sec) or unsynchronized clocks from 10.25.117.29
	Line 4371: Oct-29 03:25:57  [Warning] Collector: Packet from 1730143542, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
	Line 4377: Oct-29 03:40:58  [Warning] Collector: Packet from 1730144443, long delay (15 sec) or unsynchronized clocks from 10.25.117.12
```
Please bring the clock in sync. More info you can find here: https://www.ibm.com/docs/en/storage-scale/5.1.9?topic=monitoring-using-performance-tool

Also I see that the pmcollector, from which you provided the logs, has many query requests from gpfs gui. You can try to setup and use the grafana-bridge on second pmcollector. (Don't forget to stop grafana-bridge on this node).
