### ISSUE TITLE
Grafana dashboard update.

### ISSUE THREAD

**Issue by christiansenandi** [IBM/ibm-spectrum-scale-bridge-for-grafana#34]
Hi Helene,

As agreed, here is a ticket to track the updates for the grafana dashboard.

/Andi Christiansen

**Comment by Helene** [comment]
Andi,
please check you are using the latest dashboards version from the github. I just imported the Main Dashboard, Network and NSD Server dashbooards from the "examples/Default_Dashboards_set" in my fresh installed Grafana instance. It looks like all working fine. During the import procedure the Grafana asks authomatically, which datasource should be selected for the particular dashboard
![import_ds](https://user-images.githubusercontent.com/22845495/123558288-cd560e00-d795-11eb-9b31-62930584a4d2.png)

after opening of the dashboard, the datasource is correctly updated
![network_ds](https://user-images.githubusercontent.com/22845495/123558343-faa2bc00-d795-11eb-8b84-c652f6b67b6a.png)
also each particular query has resolved the datasource template variable correctly
![query_ds](https://user-images.githubusercontent.com/22845495/123558382-2e7de180-d796-11eb-85b2-9b8f8d73713a.png)

If you still have issues with the datasource update, after importing the latest version of the dashboards, please write me which dashboard exactly is causing trouble.

Greetings,
Helene
