### ISSUE TITLE
Import example dashboards instructions

### ISSUE THREAD

**Issue by leoauri** [IBM/ibm-spectrum-scale-bridge-for-grafana#48]
Hi, it is impractical importing each of the many example dashboards individually, and this is the workflow linked to by the README.  Therefore I suggest some pointer to the file `/etc/grafana/provisioning/dashboards/sample.yaml` which gives an example of adding a folder of dashboards for automatic provisioning.  Cheers, Leo

**Comment by Helene** [comment]
@leoauri good catch ! I'll expand the documentation about importing dashboards with more hints&tips

**Comment by leoauri** [comment]
Great!

**Comment by Helene** [comment]
Please check the following article https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/wiki/Make-usage-of-Grafana-Provisioning-feature#provision-the-example-dashboards-bundle-collection-with-folders-structure-to-grafana
