### ISSUE TITLE
Failed to connection to pmcollector: name 'request' is not defined, quitting

### ISSUE THREAD

**Issue by antzjm** [IBM/ibm-spectrum-scale-bridge-for-grafana#54]
Dear IBM support team, I meet some issue when I want to use scale bridge for grafana. The python script return error info "failed to connect to pmcollector". I just wonder what is the meaning of apikeyname and apikeyvalue. How can I get the correct value to connect pmcollector? My GPFS version == 5.0.1.1

**Comment by Helene** [comment]
> Hi, IBM support team. This issue has been open for a long time. I just wonder which tag of bridge-grafana can adapt to my gpfs version.

Please check the [SUPPORT_MATRIX.md](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/blob/master/docs/SUPPORT_MATRIX.md) doc for the version info.
In your case gpfs < 5.0.3.2 you have to use the [Version 4](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/tree/v4.0), but I would you highly recommend to upgrade your gpfs system at least to 5.0.5 latest FP and then use the Ibm Spectrum Scale Bridge for Grafana [Version 6.1.4](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/releases/tag/v6.1.4)
