### ISSUE TITLE
How to increase GUI metrics refersh frequency?

### ISSUE THREAD

**Issue by antzjm** [IBM/ibm-spectrum-scale-bridge-for-grafana#57]
Hello, IBM support team. Is there any solution to increase metrics data refresh frequence? We meet a problem that the timestamp of data display at GUI is 5mins later than system time.

**Comment by Helene** [comment]
Hi, 
could you please describe your question more precise, provide screenshots, etc.
Thanks,
Helene

**Comment by antzjm** [comment]
![截取图片_20211215175856](https://user-images.githubusercontent.com/32393135/146165379-0b52ba39-7d92-4c27-aefb-50e9c28dcb3e.png)

**Comment by antzjm** [comment]
@Helene As you can see, the neweset data is later 5 mins than PC time.

**Comment by Helene** [comment]
You are looking at **IBM Spectrum Scale GUI** interface. The **IBM Spectrum Scale GUI** interface and the **IBM Spectrum Scale bridge for Grafana** are different applications.
For questions about the  **IBM Spectrum Scale GUI** check the [IBM Knowledge Center docs](https://www.ibm.com/docs/en/spectrum-scale/5.0.5?topic=data-performance-monitoring-using-spectrum-scale-gui) and contact the official IBM Spectrum Scale Product Support.

**Comment by antzjm** [comment]
![1111](https://user-images.githubusercontent.com/32393135/146290580-a64864fa-1d2b-432f-9711-aaf1b9e56802.png)

**Comment by antzjm** [comment]
@Helene I guess this the same issue with GUI and bridge-grafana. So I wonder does it matter with pmcollector?

**Comment by Helene** [comment]
@antzjm - no, grafana-bridge and GUI do use differet source code logic.
Your grafana-bridge dashboard refresh interval is set to 15 minutes:
![image](https://user-images.githubusercontent.com/22845495/146531118-169c763d-ad5b-4bd2-8087-6ed002bb6cb8.png)
compare with my dashboard:
![image](https://user-images.githubusercontent.com/22845495/146531728-f7866b9c-07c4-4c10-926b-381cdb1de678.png)
For more info please read Grafana documentation https://grafana.com/docs/grafana/latest/troubleshooting/troubleshoot-dashboards/

**Comment by antzjm** [comment]
@Helene No, I guess you have misunderstand my intentions. The refresh internal of grafana does not matter with this issue. Although I set refresh internal to 5s, I still only see data about five minutes ago.
