### ISSUE TITLE
Where I can know the mean of all metrics?

### ISSUE THREAD

**Issue by antzjm** [IBM/ibm-spectrum-scale-bridge-for-grafana#58]
Hi, IBM support team. I have installed scale-bridge-for-grafana into my env. And I send /api/suggest request to get all metrics. I wonder where I can refer what's the mean of those metrics.

**Comment by Helene** [comment]
The /api/suggest endpoint is exclusively for Grafana auto-complete suggestion  (https://grafana.com/docs/grafana/latest/datasources/opentsdb/#auto-complete-suggestions)

The list of supported metrics you can find [here](https://www.ibm.com/docs/en/spectrum-scale/5.1.2?topic=tool-list-performance-metrics)
