### ISSUE TITLE
sensor for some metrics is disabled

### ISSUE THREAD

**Issue by antzjm** [IBM/ibm-spectrum-scale-bridge-for-grafana#59]
Hi, IBM support team. I have meet an issue that when i query some metrics that bridge server return 400 code. The log print info that xxx metrics is disabled. But I have modify pmcollector.cfg to enable this metric. But still can not solve this issue.

**Comment by ps20renar** [comment]
Hallo antzjm,
you must change the ZIMONSensor.cfg files and reload it. Not the PMcollector.cfg.
https://www.ibm.com/docs/en/spectrum-scale/5.1.4?topic=sensor-manual-configuration
