### ISSUE TITLE
Error creating a data source in Grafana 6.6

### ISSUE THREAD

**Issue by FLATT-Dev** [IBM/ibm-spectrum-scale-bridge-for-grafana#6]
The bridge runs on localhost default port 4242. I got "server started" message
In Grafana, when  I click "Test and Save" button I get an error:
 
Test1 plugin failed
Error: [$injector:unpr] Unknown provider: eProvider <- e http://errors.angularjs.org/1.6.9/$injector/unpr?p0=eProvider%20%3C-%20e
Any ideas ? Is this the Grafana issue or the plugin  or the bridge?

**Comment by Helene** [comment]
Hello,
the message "server started" is an indicator that the bridge runs.

It looks like you are running in the Grafana issue published there:
https://github.com/grafana/grafana/issues/21770

**Comment by FLATT-Dev** [comment]
Thank you!
Andy

**Comment by Helene** [comment]
l think this issue can be closed
