### ISSUE TITLE
pmcollector version 5.1.4-0 uses unix sockets 

### ISSUE THREAD

**Issue by denneb1** [IBM/ibm-spectrum-scale-bridge-for-grafana#66]
Hello, 
After upgrading to the 5.4.1 version of spectrum scale, the pmcollector does not provides a queryinterface anymore, only an unix socket.
Is it possible to use the bridge with this unix socket (/var/run/perfmon/pmcollector.socket) or is this version not supported  yet?
Thanks!

**Comment by Helene** [comment]
Hello,
first of all you need to check in the [SUPPORT_MATRIX](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/blob/master/docs/SUPPORT_MATRIX.md) for the bridge version supporting the IBM Spectrum Scale version which is in your usage. (For IBM Spectrum Scale 5.4.1 the bridge version[v7.0.6](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/releases/tag/v7.0.6) should be fine)
You will also need to generate  scale_grafana API-key on the Spectrum Scale side and include the key value in the bridge settings. Read the [following article](https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/wiki/Configuring-a-performance-monitoring-API-key-for-the-IBM-Spectrum-Scale-Performance-Monitoring-Bridge) in the **IBM Spectrum Scale bridge for Grafana Wiki**. This API key will allow the bridge to talk to pmcollector over unix socket.

**Comment by denneb1** [comment]
Hi Helene,
Thanks for your answer. 
However, the documentation you are pointing me to is using the port 9980 on the localhost interface, not an unix socket file.
What i was trying to say is that the pmcollector now seems to only expose the socket file /var/run/perfmon/pmcollector.socket to accept requests. I don't see where we can configure the grafana bridge to use this file instead of the localhost:9980 address.

**Comment by Helene** [comment]
> Hi Helene, Thanks for your answer. However, the documentation you are pointing me to is using the port 9980 on the localhost interface, not an unix socket file. What i was trying to say is that the pmcollector now seems to only expose the socket file /var/run/perfmon/pmcollector.socket to accept requests. I don't see where we can configure the grafana bridge to use this file instead of the localhost:9980 address.

The grafana bridge v7.0.6 does it automatically. Important, you have generated scale_grafana API key on the scale side and passed through the API Key value to the bridge config

**Comment by denneb1** [comment]
I have correctly generated the api key and added it to the bridge config. But i keep getting the following error when i start the bridge.
I did a small test and the bridge is sending a request to the 9980 port, not to the /var/run/perfmon/pmcollector.socket socket.
Apart from the apiKey i am using the default config. Is there something i missed?

```
2022-08-02 14:51:16,597 - bridgeLogger - INFO     -  *** IBM Spectrum Scale bridge for Grafana - Version: 7.0.6 ***
2022-08-02 14:51:16,597 - bridgeLogger - MOREINFO - zimonGrafanaItf invoked with parameters:
port=4242
protocol=http
server=localhost
serverPort=9980
retryDelay=60
apiKeyName=scale_grafana
caCertPath=False
includeDiskData=True
logPath=/var/log/zimon/
logLevel=10
logFile=zserver.log
2022-08-02 14:51:16,598 - bridgeLogger - DEBUG    - readSensorsConfigFromMMSDRFS attempt to read /var/mmfs/gen/mmsdrfs
2022-08-02 14:51:16,599 - bridgeLogger - DEBUG    - __do_RESTcall invoke __ params: perfmon/topo GET None
2022-08-02 14:51:16,599 - bridgeLogger - DEBUG    - createRequestDataObj __ created request
2022-08-02 14:51:16,600 - bridgeLogger - WARNING  - Perfmon RESTcall error __ Server responded: 503 Connection refused from server
2022-08-02 14:51:16,600 - bridgeLogger - ERROR    - QueryHandler: getTopology returns no data.
```

**Comment by Helene** [comment]
It looks like you have an issue on the IBM Spectrum Scale Side (Connection refused) . Are you running the bridge on the pmcollector node or remote one? If you are running locally, then I can provide you some instructions how to increase traces of mmsysmon daemon, to see what is the reason the daemon refuses this communication. Basically with switching to unix domain socket we did introduce the api key authentication verification. This verification is done by mmsymon. That means, the request from the bridge is sent over REST API to 9980. mmsysmon daemon is listening on this port, and does verify api key for each incomming request. Finally it sends the request to unix domain socket. The best way, to continue investigation would be, an opened issue by IBM Spectrum Scale support. You can reference to this conversation in the ticket, support team will contact me and I can provide you some instructions for the next steps in the problem investigation.
