### ISSUE TITLE
Did you mean CloudWatch ?

### ISSUE THREAD

**Issue by didorins** [IBM/ibm-spectrum-scale-bridge-for-grafana#67]
**Describe the bug**
Not actual bug in code, but more of cosmetic typo in readme

**To Reproduce**
1. Go to 'Main repo'
2. Click on 'Image in readme'
3. Scroll down to 'bottom of repo'
4. See misspelled "CoudWatch"

**Expected behavior**

**Screenshots**
https://github.com/IBM/ibm-spectrum-scale-bridge-for-grafana/blob/master/docs/bridge_overview.PNG

**Comment by Helene** [comment]
Yeah, it looks like a typo :) Thanks for reporting this!
