### ISSUE TITLE
initialization failures with 7.0.4

### ISSUE THREAD

**Issue by jkaitschuck** [IBM/ibm-spectrum-scale-bridge-for-grafana#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - IBM Spectrum Scale system type:
    - [ ] IBM Spectrum Scale classic cluster.
    - [ ] IBM Spectrum Scale Container Native Storage Access (CNSA).
    - [ ] IBM Elastic Storage Server (ESS).
 - IBM Spectrum Scale cluster version:
 - IBM Spectrum Scale bridge for Grafana version:
 - Grafana version:
 - OS Grafana is installed on:

**Additional context**

**Comment by jkaitschuck** [comment]
with GPFS -> gpfs.base-5.1.1-4.x86_64 CNS
and <>

python/3.6.10
CherryPy 18.6.1

log displays ....

 port=4242
protocol=http
server=localhost
serverPort=9980
apiKeyName=scale_grafana
includeDiskData=False
logPath=/var/log/ibm_bridge_for_grafana
logLevel=5
logFile=zserver.log
2022-10-30 13:13:11,449 - bridgeLogger - DEBUG    - readSensorsConfigFromMMSDRFS attempt to read /var/mmfs/gen/mmsdrfs
2022-10-30 13:13:11,450 - bridgeLogger - DEBUG    - __do_RESTcall invoke __ params: perfmon/topo GET None
2022-10-30 13:13:11,450 - bridgeLogger - DEBUG    - createRequestDataObj __ created request
2022-10-30 13:13:11,452 - bridgeLogger - MOREINFO - Server internal error occurred. Reason: can't set attribute
2022-10-30 13:13:11,452 - bridgeLogger - ERROR    - Metadata could not be retrieved. Check log file for more details, quitting

===

?

pmcollector is running and mmperfmon from the node queries just fine.

**Comment by Helene** [comment]
on the pmcollector node please execute the following commands and paste the output here.
1. mmdiag --version
2. mmperfmon config show

**Comment by jkaitschuck** [comment]
I discovered the issue late Sunday. There was a typo in the config file,.
V6 of the code didn’t return the metadata collection error until the program
was killed, V7 returned the metadata collection error in the log.

We are a bit behind the curve version wise on this particular system.



Thanks.


On Nov 1, 2022, at 11:49 AM, Helene Wassmann ***@***.******@***.***>> wrote:



on the pmcollector node please execute the following commands and paste the output here.

  1.  mmdiag --version
  2.  mmperfmon config show

**Comment by Helene** [comment]
Can we close this ticket?

**Comment by jkaitschuck** [comment]
yes … and thank you.


On Nov 1, 2022, at 11:56 AM, Helene Wassmann ***@***.******@***.***>> wrote:



Can we close this ticket?
