### ISSUE TITLE
dashboards uses random walk input

### ISSUE THREAD

**Issue by janfrode** [IBM/ibm-spectrum-scale-bridge-for-grafana#8]
As a newbie Grafana user, it's been very difficult to understand why the provided dashboards set doesn't work. They seem to all be using random walk data. None of the "default dashboards" prompt for any data source. Others prompt, but still use random walk.

Importing f.ex. the 

    example_dashboards_bundle/Predefined\ Basic\ Dashboards/File System Capacity View-1554293302658.json

prompts me for a data-source, but when checking the resulting graphs, they still list random walk. 

This is with Grafana v7.0.3

**Comment by Helene** [comment]
fixed by commit bcd8f85befc6c76117400185f2b5e79df45033b6
